#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Apply LOWESS smoothing to annual daily EVI2 time series over cropland pixels.

Daily EVI2 composites are read from the merged files generated by the
90th-percentile NDVI compositing script. Missing daily observations are filled
using one-dimensional interpolation before LOWESS smoothing.

The LOWESS span is fixed at 0.095, matching the value used in the manuscript.
Only cropland pixels (land-cover class 10) are processed.

Output values are stored as int16 after multiplication by 10,000.
Missing values are stored as -9999.
"""

from argparse import ArgumentParser
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import numpy as np
import statsmodels.api as sm
import tifffile
from tqdm import tqdm


# =============================================================================
# User settings
# =============================================================================

# Replace these paths with locations in the local environment.
INPUT_DIR = Path("/path/to/output/90percentile_NDVI")
LANDCOVER_FILE = Path("/path/to/landcover/SE.tif")
OUTPUT_DIR = Path("/path/to/output/Cropcycle")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Analysis grid
HEIGHT = 3200
WIDTH = 3500
N_DAYS = 365

# Land-cover class used to identify cropland pixels.
CROPLAND_CLASS = 10

# LOWESS settings used in the analysis.
LOWESS_SPAN = 0.095
ROBUST_ITERATIONS = 0
MIN_VALID_OBSERVATIONS = 3

# Output settings.
SCALE_FACTOR = 10000.0
FILL_VALUE = -9999

# Parallel-processing defaults. These affect computational performance only.
DEFAULT_N_JOBS = 16
DEFAULT_CHUNK_SIZE = 4000


def read_year_evi2(year):
    """
    Read one year of daily EVI2 composites.

    Parameters
    ----------
    year : int
        Calendar year to process.

    Returns
    -------
    np.ndarray
        Daily EVI2 array with shape (365, 3200, 3500), stored as float32.
        Non-positive values and missing data are represented by NaN.
    """
    evi2 = np.full((N_DAYS, HEIGHT, WIDTH), np.nan, dtype=np.float32)
    expected_size = HEIGHT * WIDTH

    for day_index in tqdm(range(N_DAYS), desc="Read daily EVI2 files"):
        doy = day_index + 1
        input_file = INPUT_DIR / f"90_EVI2_{year}{doy:03d}.flt"

        if not input_file.exists():
            print(f"[WARN] Missing file: {input_file}")
            continue

        data = np.fromfile(input_file, dtype=np.int16)
        if data.size != expected_size:
            raise ValueError(
                f"Unexpected file size for {input_file}: "
                f"found {data.size:,} values, expected {expected_size:,}."
            )

        daily = data.reshape(HEIGHT, WIDTH)
        daily = daily.astype(np.float32) / SCALE_FACTOR
        daily[daily <= 0] = np.nan

        evi2[day_index] = daily

    return evi2


def interpolate_missing_values(y, x):
    """
    Fill missing values in a one-dimensional daily time series.

    Interior gaps are linearly interpolated. Before the first and after the
    last valid observation, ``numpy.interp`` uses the nearest valid endpoint.
    Pixels with fewer than three valid observations are not processed.
    """
    finite = np.isfinite(y)
    n_valid = int(finite.sum())

    if n_valid < MIN_VALID_OBSERVATIONS:
        return None

    if n_valid == y.size:
        return y.astype(np.float32, copy=False)

    return np.interp(x, x[finite], y[finite]).astype(np.float32, copy=False)


def process_chunk(flat_evi2, pixel_indices, x):
    """
    Apply interpolation and LOWESS smoothing to a chunk of cropland pixels.

    Parameters
    ----------
    flat_evi2 : np.ndarray
        EVI2 array with shape (day, pixel).
    pixel_indices : np.ndarray
        Flattened pixel indices included in this chunk.
    x : np.ndarray
        Daily time coordinate.

    Returns
    -------
    tuple
        Pixel indices and smoothed int16 values with shape (day, chunk_size).
    """
    lowess = sm.nonparametric.lowess
    n_days = x.size

    output = np.full(
        (n_days, pixel_indices.size),
        FILL_VALUE,
        dtype=np.int16,
    )

    chunk_evi2 = flat_evi2[:, pixel_indices]

    for column in range(pixel_indices.size):
        interpolated = interpolate_missing_values(chunk_evi2[:, column], x)
        if interpolated is None:
            continue

        smoothed = lowess(
            interpolated,
            x,
            frac=LOWESS_SPAN,
            it=ROBUST_ITERATIONS,
            is_sorted=True,
            return_sorted=False,
        ).astype(np.float32, copy=False)

        scaled = np.clip(
            np.rint(smoothed * SCALE_FACTOR),
            np.iinfo(np.int16).min,
            np.iinfo(np.int16).max,
        ).astype(np.int16)

        output[:, column] = scaled

    return pixel_indices, output


def main():
    """Read annual EVI2, smooth cropland pixels, and save the result."""
    parser = ArgumentParser()
    parser.add_argument("year", type=int, help="Year to process")
    parser.add_argument(
        "--n_jobs",
        type=int,
        default=DEFAULT_N_JOBS,
        help="Number of worker threads",
    )
    parser.add_argument(
        "--chunk_size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help="Number of pixels processed per chunk",
    )
    args = parser.parse_args()

    year = args.year
    x = np.arange(N_DAYS, dtype=np.float32)

    # Identify cropland pixels on the same spatial grid as the LOESS analysis.
    landcover = tifffile.imread(LANDCOVER_FILE)
    if landcover.shape != (HEIGHT, WIDTH):
        raise ValueError(
            f"Unexpected land-cover shape: {landcover.shape}; "
            f"expected {(HEIGHT, WIDTH)}."
        )

    cropland_indices = np.flatnonzero((landcover == CROPLAND_CLASS).ravel())
    n_cropland = cropland_indices.size
    print(f"Cropland pixels: {n_cropland:,} / {HEIGHT * WIDTH:,}")

    # Read annual EVI2 and flatten the spatial dimensions for pixel-wise LOWESS.
    evi2 = read_year_evi2(year)
    flat_evi2 = evi2.reshape(N_DAYS, -1)

    # Store the smoothed annual time series in a binary int16 file.
    output_file = OUTPUT_DIR / f"LOESS_EVI2_{year}.flt"
    output_memmap = np.memmap(
        output_file,
        mode="w+",
        dtype=np.int16,
        shape=(N_DAYS, HEIGHT * WIDTH),
    )
    output_memmap[:] = FILL_VALUE

    chunks = [
        cropland_indices[start:start + args.chunk_size]
        for start in range(0, n_cropland, args.chunk_size)
    ]
    print(f"Chunks: {len(chunks)} (chunk size={args.chunk_size})")
    print(f"LOWESS span: {LOWESS_SPAN}")

    with ThreadPoolExecutor(max_workers=args.n_jobs) as executor:
        futures = [
            executor.submit(process_chunk, flat_evi2, chunk, x)
            for chunk in chunks
        ]

        for future in tqdm(
            as_completed(futures),
            total=len(futures),
            desc="LOWESS",
        ):
            pixel_indices, result = future.result()
            output_memmap[:, pixel_indices] = result

    output_memmap.flush()
    print(f"Saved: {output_file}")


if __name__ == "__main__":
    main()
